# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

#foobar

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    # IS THIS STILL VALID?
    # npm dedupe # because reasons, without that zopfli(jest>request) fails and all goes to hell
  displayName: 'Install node modules'

- script: |
    npm run test
  displayName: 'Run Tests'

- script: |
    npm run build
  displayName: 'Build'
