# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript



# some comment goes here

# and another one

# and another one


pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    # IS THIS STILL VALID?
    # npm dedupe # because reasons, without that zopfli(jest>request) fails and all goes to hell
  displayName: 'Install node modules'

- script: |
    npm run test
  displayName: 'Run Tests'

- script: |
    npm run pack
  displayName: 'Pack for npmjs registry publish'

- script: |
    pwd
  displayName: 'Whaere ios this hapenning'

- script: |
    ls -al
  displayName: 'what is in here'


# - task: CopyFiles@2
#     displayName: 'Copy files into artifact location'
#     inputs:
#         SourceFolder: build
#         Contents: '**/*'
#         TargetFolder: '$(build.artifactstagingdirectory)/packed-uxi'

# Publish Build Artifacts
# Publish build artifacts to Azure Artifacts/TFS or a file share

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifact'
  inputs:
    # pathtoPublish: '$(Build.ArtifactStagingDirectory)/packed-uxi'
    pathtoPublish: 'build'
    artifactName: 'packed-uxi'
    # publishLocation: 'Container' # Options: container, filePath
    #targetPath: # Required when publishLocation == FilePath
    #parallel: false # Optional
    #parallelCount: # Optional
