# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

# some comment



# some comment goes here

# and another one

# and another one


pool:
  vmImage: 'Ubuntu 16.04'


steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'


- script: |
    npm install
  displayName: 'Install node modules'


- script: |
    npm run test
  displayName: 'Run Tests'


# patch version before packing, if this is on master artifact will already
# have the correct (next) version number to deploy to npmjs/release on git
- script: |
    npm version patch -m "bump to v %s for release" ## creates the "tagged release commit" (git tag)
  displayName: 'patch version for git/npmjs realease'


- script: |
    npm run pack
  displayName: 'Pack for npmjs registry publish'


# - task: CopyFiles@2
#     displayName: 'Copy files into artifact location'
#     inputs:
#         SourceFolder: build
#         Contents: '**/*'
#         TargetFolder: '$(build.artifactstagingdirectory)/packed-uxi'

# Publish Build Artifacts
# Publish build artifacts to Azure Artifacts/TFS or a file share

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifact'
  inputs:
    # pathtoPublish: '$(Build.ArtifactStagingDirectory)/packed-uxi'
    pathtoPublish: './'
    artifactName: 'uxi'
    # publishLocation: 'Container' # Options: container, filePath
    #targetPath: # Required when publishLocation == FilePath
    #parallel: false # Optional
    #parallelCount: # Optional

# - task: PublishBuildArtifacts@1
#   displayName: 'Publish artifact (packed uxi lib)'
#   inputs:
#     # pathtoPublish: '$(Build.ArtifactStagingDirectory)/packed-uxi'
#     pathtoPublish: 'build'
#     artifactName: 'packed-uxi'
#     # publishLocation: 'Container' # Options: container, filePath
#     #targetPath: # Required when publishLocation == FilePath
#     #parallel: false # Optional
#     #parallelCount: # Optional
