# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

# some comment






# some comment goes here

# and another one

# and another one


pool:
  vmImage: 'Ubuntu 16.04'


steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

## creds

- script: |
    cat .git/config
  displayName: 'project git config'


- script: |
    touch ~/.gitconfig
    echo '[user]' >> ~/.gitconfig
    echo '    name = Denis Florkin' >> ~/.gitconfig
    echo '    email = denisflorkin@gmail.com' >> ~/.gitconfig
  displayName: 'write git configo to file'


- script: |
    cat ~/.gitconfig
  displayName: 'system user git config'

# - script: |
#     cat /etc/gitconfig
#   displayName: 'system git config'

- script: |
    git config user.email
  displayName: 'git user.email'

- script: |
    echo $CICIMAINTAINER_NAME
  displayName: 'test env var'

# - script: |
#     echo $($CICIMAINTAINER_NAME)
#   displayName: 'test env var 2'

# - script: |
#     git log -1
#   displayName: 'git log'


# - script: |
#       git config --global user.email $CICIMAINTAINER_EMAIL
#   displayName: 'git email and name to sign version patch commit'

# - script: |
#       git config --global user.name $CICIMAINTAINER_NAME
#   displayName: 'git email and name to sign version patch commit'



- script: |
    # npm install
    # https://stackoverflow.com/questions/45022048/why-does-npm-install-rewrite-package-lock-json#answer-49011933
    npm ci
  displayName: 'Install node modules'


- script: |
    npm run test
  displayName: 'Run unit Tests'

# patch version before packing, if this is on master artifact will already
# have the correct (next) version number to deploy to npmjs/release on git
- script: |
    npm version patch -m "bump to v %s for release" ## creates the "tagged release commit" (git tag)
  displayName: 'patch version for git/npmjs realease'

# test packing
- script: |
    npm run pack
  displayName: 'Run packing for test purp.'

- script: |
    rm -rf node_modules
  displayName: 'rm node module before saving artifact.'


# - task: CopyFiles@2
#     displayName: 'Copy files into artifact location'
#     inputs:
#         SourceFolder: build
#         Contents: '**/*'
#         TargetFolder: '$(build.artifactstagingdirectory)/packed-uxi'

# Publish Build Artifacts
# Publish build artifacts to Azure Artifacts/TFS or a file share

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifact'
  inputs:
    # pathtoPublish: '$(Build.ArtifactStagingDirectory)/packed-uxi'
    pathtoPublish: './'
    artifactName: 'uxi'
    # publishLocation: 'Container' # Options: container, filePath
    #targetPath: # Required when publishLocation == FilePath
    #parallel: false # Optional
    #parallelCount: # Optional

# - task: PublishBuildArtifacts@1
#   displayName: 'Publish artifact (packed uxi lib)'
#   inputs:
#     # pathtoPublish: '$(Build.ArtifactStagingDirectory)/packed-uxi'
#     pathtoPublish: 'build'
#     artifactName: 'packed-uxi'
#     # publishLocation: 'Container' # Options: container, filePath
#     #targetPath: # Required when publishLocation == FilePath
#     #parallel: false # Optional
#     #parallelCount: # Optional
